@Tournament_HostAddress = http://localhost:5294

GET {{Tournament_HostAddress}}/tournaments/
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjExZTZhM2I3LTlmNzQtNDNkYy05MzFjLWU1NGIwZjUwYmJiZSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJpbGlldjM1IiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoiZGltaXRAYWJ2LmJnIiwiQXNwTmV0LklkZW50aXR5LlNlY3VyaXR5U3RhbXAiOiJTM1ZXVktKWFNDQzZYVFpGSkxCVkxYQVVDUjNRSVhKTiIsImFtciI6InB3ZCIsIm5iZiI6MTcyNDQxNjEzMCwiZXhwIjoxNzI0NDE2NzMwfQ.B_bLoV8ICEGnRLeV29e54x6i0GqKHr3z1CehB6c2WC0
Accept: application/json

###
